# Generated by Django 3.1 on 2020-09-12 09:35

from django.db import migrations, models
import pdfCombiner.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('pdf_file_name', models.CharField(max_length=1000)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=pdfCombiner.models.pdf_path)),
                ('total_pages', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
