# Generated by Django 3.1 on 2020-09-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfCombiner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file_name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
