# Generated by Django 3.1 on 2020-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfCombiner', '0002_auto_20200907_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
