# Generated by Django 3.1 on 2020-09-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfCombiner', '0003_pdf_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file_name',
            field=models.CharField(max_length=40),
        ),
    ]
