# Generated by Django 3.1 on 2020-09-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfCombiner', '0004_auto_20200909_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='total_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
