# Generated by Django 3.1 on 2020-09-09 16:36

from django.db import migrations, models
import pdfCombiner.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfCombiner', '0005_pdf_total_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=pdfCombiner.models.pdf_path),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file_name',
            field=models.CharField(max_length=500),
        ),
    ]
