# Generated by Django 3.1 on 2020-09-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfCombiner', '0006_auto_20200909_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='pdf_file_name',
            field=models.CharField(max_length=1000),
        ),
    ]
